name: VillageMiner
main: com.memoritta.villageminer.VillageMinerPlugin
version: 1.0
api-version: 1.15
commands:
  spawnminer:
    description: Spawns a miner.
    usage: /spawnvillageminer
  killminer:
    description: Kill miner.
    usage: /killvillageminer