name: VillageMiner
main: com.memoritta.villageminer.VillageMinerPlugin
version: 1.0
api-version: 1.15
commands:
  spawnvillager:
    description: Spawns a villager that follows the player around.
    usage: /spawnvillageminer
